name: Plugin PHPUnit Tests

on: 
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          #MYSQL_ROOT_PASSWORD: root
          #MYSQL_DATABASE: wordpress_test
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=10
        #--health-cmd="mysqladmin ping --silent"

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: mbstring, mysql, mysqli
        tools: composer

    - name: Install Subversion (svn)
      #run: 
      run: |
        sudo apt-get update
        sudo apt-get install -y subversion

    - name: Reset test DB
      run: mysql -h127.0.0.1 -uroot -proot -e "DROP DATABASE IF EXISTS wordpress_test;"      
      #run: mysql -h127.0.0.1 -uroot -proot -e "CREATE DATABASE wordpress_test;"
    
    - name: Install WP Test Suite
      run: bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 latest
      #run: bash bin/install-wp-tests.sh wordpress_test root root 127.0.0.1 latest
      #run: bash bin/install-wp-tests.sh wordpress_test root '' localhost latest

    - name: Install Composer deps
      run: composer install --no-interaction --prefer-dist

    - name: Run PHPUnit
      run: vendor/bin/phpunit

